      tikv:
        storageClassName: fast-disks
        image: pingcap/tikv:v5.3.0
        # more refer to: https://github.com/tikv/tikv/blob/master/etc/config-template.toml
        requests:
          cpu: 8000m
          memory: 32Gi
          storage: 2000Gi
        limits:
          cpu: 8000m
          memory: 32Gi
          storage: 2000Gi
        service:
          type: NodePort
        config: |
          ## Log levels: trace, debug, info, warning, error, critical.
          ## Note that `debug` and `trace` are only available in development builds.
          [storage]
          reserve-space = 0
          [storage.block-cache]
          shared = true
          capacity = "12G"
          [rocksdb.defaultcf]
          compression-per-level = ["no", "no", "no", "no", "no", "no", "no"]
          [rocksdb.writecf]
          compression-per-level = ["no", "no", "no", "no", "no", "no", "no"]
          [rocksdb.lockcf]
          compression-per-level = ["no", "no", "no", "no", "no", "no", "no"]
          [raftstore]
          apply-low-priority-pool-size = 4
          [server]
          raft-client-queue-size = 81920
