generateName: write-throughput-test-tidb-
resourcePool: quantify_products
reclaimPolicy:
  gcStrategy:
    onFailure:
      artifact:
        monitor: true
        log: true
    onSuccess:
      artifact:
        monitor: true
        log: true

items:
  - name: write-throughput-test # 资源对象项名称
    type: TIDB_CLUSTER # 资源对象类型
    spec:
      # 如果使用一个具体的版本, 例如 v5.0.1 而不是 nightly, master 等, 通过设置 IfNotPresent 可以加速创建速度
      imagePullPolicy: IfNotPresent
      pd:
        replicas: 1
        storageClassName: fast-disks
        image: pingcap/pd:v5.3.0
        # more refer to: https://github.com/tikv/pd/blob/master/conf/config.toml
        # config is string type and toml format, I prefer uses https://www.convertsimple.com/convert-yaml-to-toml/ to transfer yaml to toml
        requests:
          cpu: 4000m
          memory: 8Gi
          storage: 500Gi
        limits:
          cpu: 4000m
          memory: 8Gi
          storage: 500Gi
        service:
          type: NodePort
        config: |
          [log]
          level = "info"
      tidb:
        replicas: 1
        storageClassName: fast-disks
        image: pingcap/tidb:v5.3.0
        requests:
          cpu: 8000m
          memory: 16Gi
          storage: 500Gi
        limits:
          cpu: 8000m
          memory: 16Gi
          storage: 500Gi
        service:
          type: NodePort
        securityContext:
          capabilities:
            add: ["SYS_ADMIN", "SYS_PTRACE", "NET_ADMIN"]
        config: |
          [log]
          # Log level: debug, info, warn, error, fatal.
          level = "info"
